Clean Jenkins scripts
Azure/azure-devops-utils pull request #10
Opened 2017-03-07 23:15 UTC by clguimanMSFT

2017-03-07 23:15 UTC, msftclas commented
@clguimanMSFT,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-03-08 00:16 UTC, ejizba requested changes

2017-03-08 00:16 UTC, ejizba commented on jenkins/add-docker-build-job.sh
> +    credentials_id="docker_credentials"
I recommend setting the default values before the parameter while loop for a few reasons:
1. Then you don't have to wrap it in a 'if' clause because it will just be overwritten by user input later
2. If the user wants to explicitly set something to an empty string, they still can (If the string can't be empty, then call 'throw_if_empty' and the user will get an error, which I think is better than ignoring their input and using our default)

2017-03-08 00:16 UTC, ejizba commented on jenkins/add-docker-build-job.sh
> +credentials_xml=$(echo "${credentials_template}" | sed \
If you want a simpler way to do this, you can look at the 'Substring Replacement' section from [here](http://tldp.org/LDP/abs/html/string-manipulation.html)

I tested it out with this
```bash
test_var='!@#$%^&*()|[]\{}/?><fdsa'
x='<test><a>{test_var}</a><b>{test_var}</b></test>'
x=${x//'{test_var}'/$test_var}
echo $x
```

I don't think sed would handle those characters correctly so it is probably more robust, too

2017-03-08 00:16 UTC, ejizba commented on jenkins/add-docker-build-job.sh
> +# can't store the output in a variable because it will remove the line breaks and it will break the groovy script
See this [stack overflow question](http://stackoverflow.com/questions/613572/capturing-multiple-line-output-into-a-bash-variable)

You just have to wrap your variable in quotes when you reference it and line breaks should be preserved

2017-03-08 00:16 UTC, ejizba commented on jenkins/add-docker-build-job.sh
> +# can't store the output in a variable because it will remove the line breaks and it will break the groovy script
Best practice is to wrap every variable in quotes when you reference it, but I still forget sometimes haha

2017-03-08 00:16 UTC, ejizba commented on quickstart_template/jenkins-to-acr.sh
> +#!/bin/bash
In my head, the naming convention for these files was the same name as the folder in the quickstart repo. So this one would be called "201-jenkins-to-azure-container-registry.sh"

2017-03-08 00:16 UTC, EricJizbaMSFT commented on quickstart_template/jenkins-to-acr.sh
> +  --include_docker_build_pipeline|-i    : Include a docker build pipeline (off by default)
--include_docker_build_pipeline is in here twice

2017-03-08 00:16 UTC, EricJizbaMSFT commented on quickstart_template/jenkins-to-acr.sh
> +sudo service docker restart
The script above starts docker, so you shouldn't have to restart it, right? When I look at my logs for that script, I see "docker start/running, process 48680"

2017-03-08 00:16 UTC, EricJizbaMSFT commented on quickstart_template/jenkins-to-acr.sh
> +sudo curl -sSL https://get.docker.com/ | sh
nit: can you move the docker steps before the "install jenkins" section into a "install docker" section?

2017-03-08 00:16 UTC, EricJizbaMSFT commented on quickstart_template/jenkins-to-acr.sh
> +./${add_docker_build_job_script_name} -j "http://localhost:8080/" -ju "admin" -jp "${admin_password}" -g "${git_url}" -r "${registry}" -ru "${registry_user_name}"  -rp "${registry_password}" -rr "${v
You can run a script without saving it to disk like this:

`curl --silent "${base_remote_jenkins_scripts}/add-docker-build-job.sh" | sudo bash -s -- -j "http://localhost:8080/" -ju "admin" -jp "${admin_password}" -g "${git_url}" -r "${registry}" -ru "${registry_user_name}"  -rp "${registry_password}" -rr "${vm_user_name}/myfirstapp"`

NOTE: the '--' is important and I've missed it before. It separates the parameters for 'sudo bash' and the parameters for the downloaded script.

2017-03-08 17:43 UTC, ejizba approved these changes

2017-03-08 17:43 UTC, EricJizbaMSFT commented on quickstart_template/201-jenkins-to-azure-container-registry.sh
> +add_docker_build_job_script_name="add-docker-build-job.sh"
Can delete this variable

2017-03-08 19:07 UTC, clguimanMSFT commented
@PeterJausovec the Jenkins scripts now expect the arguments in a different way. Please have a look and let me know if this works for you

2017-03-08 19:14 UTC, merged

2017-03-08 19:19 UTC, PeterJausovec commented on jenkins/add-docker-build-job.sh
> +job_xml=${job_xml//'{insert-cr-url}'/${registry}}
consider renaming to ```insert-registry-url``` in the .xml file just to keep it consistent

2017-03-08 19:21 UTC, PeterJausovec commented on jenkins/add-docker-build-job.sh
> +retry_until_successful cat job.xml | java -jar jenkins-cli.jar -s ${jenkins_url} create-job ${job_short_name} --username ${jenkins_user_name} --password ${jenkins_password}
could you could do the same here as you did with the ```credentials_xml```. (```echo "${job_xml}"```)?

2017-03-08 19:22 UTC, clguimanMSFT commented on jenkins/add-docker-build-job.sh
> +retry_until_successful cat job.xml | java -jar jenkins-cli.jar -s ${jenkins_url} create-job ${job_short_name} --username ${jenkins_user_name} --password ${jenkins_password}
no, the groovy script has to have newlines in it and for some reason echo "${job_xml}" broke the line endings

2017-03-08 19:22 UTC, clguimanMSFT commented on jenkins/add-docker-build-job.sh
> +job_xml=${job_xml//'{insert-cr-url}'/${registry}}
I'll fix it in another PR

2017-03-08 19:24 UTC, PeterJausovec commented on quickstart_template/201-jenkins-to-azure-container-registry.sh
> +if [[ "${include_docker_build_pipeline}" != "1" ]]
nit: just for consistency with the if statement above, you might want to invert this condition

2017-03-08 19:25 UTC, PeterJausovec commented on jenkins/add-docker-build-job.sh
> +retry_until_successful cat job.xml | java -jar jenkins-cli.jar -s ${jenkins_url} create-job ${job_short_name} --username ${jenkins_user_name} --password ${jenkins_password}
👍